### ISSUE TITLE
Zambretti values always None

### ISSUE THREAD

**Issue by zacs** [briis/hass-weatherflow2mqtt#164]
### Home Assistant Version?

2022.6.6

### Add-On or Self Hosted?

Self managed Container

### Weatherflow2MQTT version?

latest

### What happened?

Was excited to start integrating the recently added Zambretti values (thanks @GlennGoddard!), but since pulling the latest stable image from docker hub two days ago, I just see `None` as the value. I don't have a Tempest (I have the older Air+Sky), in case I am perhaps missing some data needed for it? Pressure trend is there and works. Nothing useful in the logs, it just shows that sensors are all set up.

**Comment by GlennGoddard** [comment]
Did you add the new environment variables for min and max pressure?

**Comment by zacs** [comment]
Thanks @GlennGoddard -- I did not have lat/long set up. However I have added them now, and still get `None` for Zambretti values. `wind_direction_avg`, `pressure_trend`, and `sealevel_pressure` all work just fine and I see them changing over time. 

MQTT Explorer shows the entities existing just without state. Does it take some time for them to become populated?

![image](https://user-images.githubusercontent.com/27705/177913612-a113f3ec-8dde-4593-b1cb-498a04a9d238.png)

**Comment by GlennGoddard** [comment]
Do you get an output for Solar Insulation?

**Comment by GlennGoddard** [comment]
It should take less than a minute, unless there was no trend information then it could take time to establish trend data, but you say you have trend.

Do you have the ALL time min/max for various sensors?  If not then might be an SQL problem.

It should work on Air&Sky but since I only have a Tempest, that is all I could test...
I didn't say Tempest only, and I don't think anything I call is Temest only.

If you don't mind loosing some data, try a clean install...this shouldn't make a difference...but sometimes it works.  Ensure the docker volume is deleted.

I asked about Solar Insulation because if that works then I know that Latitude is formated correctly.   Did you do pressure in inHg?

**Comment by zacs** [comment]
I do indeed get solar insolation. For pressure I did not set any values (just assuming defaults would be fine for now). I will try a clean install, no worries about lost data I think.

**Comment by GlennGoddard** [comment]
I just went thru the code to make sure I didn't miss anything that would cause a 'None' return.
I think you are in the same general area (Puget Sound) as me so try putting in the Min and Max variables.  There are defaults but they may not be getting thru for some reason.  The defaults are those for the UK, those make a huge difference in the output...but in you case it 'might' give an output other than 'None'

`-e ZAMBRETTI_MIN_PRESSURE=29.046`
`-e ZAMBRETTI_MAX_PRESSURE=30.657`

Are you using Imperial or Metric?

Here is my docker run command, other than Tempest_Device and Dev build are there any other differences of relevance?
`docker run -d --name=weatherflow2mqtt --restart=unless-stopped -v /home/glenn/weatherflow_config:/data -p 0.0.0.0:50222:50222/udp -e TZ=America/Los_Angeles -e TEMPEST_DEVICE=True -e UNIT_SYSTEM=imperial -e RAPID_WIND_INTERVAL=0 -e DEBUG=False -e ELEVATION=102.108 -e LATITUDE=4x.xxxxx -e LONGITUDE=-12x.xxxxx -e WF_HOST=0.0.0.0 -e WF_PORT=50222 -e MQTT_HOST=xxx.xxx.xxx.xxx -e MQTT_PORT=1883 -e MQTT_USERNAME= -e MQTT_PASSWORD= -e MQTT_DEBUG=False -e ADD_FORECAST=True -e STATION_ID=xxxxx -e STATION_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxx -e FORECAST_INTERVAL=30 -e ZAMBRETTI_MIN_PRESSURE=29.046 -e ZAMBRETTI_MAX_PRESSURE=30.657 briis/weatherflow2mqtt:dev`

The only think I can't verify is that the Min/Max (Hi/Lo) pressures are getting to the function for you.  You have verified that all other data you have, so I think it is safe to assume it is getting to the function.

Look at one of your WeatherFlow sensors in Home Assistant and see if you have the min/max for various time intervals.  If you did a clean install and specify a config location; did you delete those files?  If you don't specify, did you delete the docker volume (it 'should' create a new volume, but you never know)

If you are imperial units, then only the elevation is in metric for the setup everything else is imperial.

**Comment by zacs** [comment]
Thanks for those values. I just added and restarted Docker and still nothing. When I started clean I just removed the image, but not the actual data folder. I just tried using a new/empty volume and that also didn't solve the problem. 

My compose environment vars are:

```
environment:
      - TZ=America/Los_Angeles
      - UNIT_SYSTEM=imperial
      - LANGUAGE=en
      - RAPID_WIND_INTERVAL=0
      - DEBUG=False
      - ELEVATION=81
      - LATITUDE=47.xx
      - LONGITUDE=-122.xx
      - ZAMBRETTI_MIN_PRESSURE=29.046
      - ZAMBRETTI_MAX_PRESSURE=30.657
      - WF_HOST=0.0.0.0
      - WF_PORT=50222
      - MQTT_HOST=x.y.z.t
      - MQTT_PORT=1883
      - MQTT_USERNAME=x
      - MQTT_PASSWORD=x
      - MQTT_DEBUG=False
      - STATION_ID=xx
      - STATION_TOKEN=xx
      - FORECAST_INTERVAL=30
```

I'll turn on debug next and see if it says anything!

**Comment by GlennGoddard** [comment]
hum....you can't check the long term stats until after midnight so.....Did you ever notice them in the past?

If @briis  still has his Air & Sky setup he can give some insight here...

Try graphing the sensors (ones from above) over small period (maybe an hour) and let's see if there are dead zones in the data (yes, I'm grasping here).

Just to verify, your Solar Insolation should be 706ish right now.  Is that close?

**Comment by zacs** [comment]
I'm grasping as well! All sensors are reporting data very consistently so I don't think it's a gap issue. For eg here is the one you asked about (value looks right). Haven't had a chance to enter debug mode but I will tonight. Seems like Air/Sky may be missing something that Tempest has. 

![image](https://user-images.githubusercontent.com/27705/178127671-c6dff393-3249-4772-967d-f79d508e14f4.jpeg)

**Comment by briis** [comment]
#### Solar values
There should be no difference wether you use AIR/SKY or TEMPEST. The data used for the calculation are all generated in the same way, it just what UDP Frame we use to gather the data - but when sending it to this module it makes no difference.
I cannot rule it out 100% that this is where the error lays, as my AIR/SKY is packed away in the Attic and unfortunately they cannot be added the the HUB I have, as the EU hubs don't support this - so I would have to find the old Hub also.

I have just pushed a new `dev` build to Docker Hub, where I have made it so that the `solar_insotlation` sensor is not dependent on the solar elevation being calculated. Instead it will calculate it directly when calculating the insolation value. I am not sure this is where the error is, but it is worth a try.
Give the new container a try, and let us know if this changes anything.

#### Zambretti
Could you try and look at your Sea Level Pressure value in HA and compare that to the Value the WeatherFlow APP is giving you. I have another user reporting they are not nearly the same - this will not affect the Solar Insulation value, but the Zambretti.

**Comment by zacs** [comment]
Just pulled the `dev` build and doesn't seem to help. Turned debug on as well and the only relevant bits are:

```
DEBUG:weatherflow2mqtt.weatherflow_mqtt:Setting payload: zambretti_number = None
DEBUG:weatherflow2mqtt.weatherflow_mqtt:Setting payload: zambretti_text = None
```

Is it possible that because the Air and Sky messages come in at different times, and the Zambretti seems to be calculated whenever the Air sends data, that it is missing values from the Sky at the same time? This seems unlikely but it's the only thing I can think of.

**Comment by GlennGoddard** [comment]
I missed the issue that was posted before yours, that pressure is off from the app and the integration.  But it is off for me as well and I get Zambretti outputs.  It must be that since the Air&Sky have different UDP broadcasts is the issue, but then other calculations should have issues as well.

Actually...the app reports Sea Level, so that is not it.

**Comment by briis** [comment]
I gave that a thought also, but as soon as there is data it is kept in memory and used going forward - having a value in the sea level pressure is a good indication of that.
I might need to get my AIR/SKY out and setup again, and see if I can replicate this.

**Comment by zacs** [comment]
Just pulled the most recent `dev` tag (I assume that includes the 3.1.1 changes), and still nothing. So strange. 

My pressure is off between the Tempest app and what I see in HA, but not by much (29.734 in HA and 30.060 in app).

**Comment by zacs** [comment]
I only have a single pressure measurment in the Tempest app, which shows 30.063, and in HA I see below. And yes positive I've pulled latest, rebuilt the whole container, it shows 27 hours old for the age. 

<img width="319" alt="image" src="https://user-images.githubusercontent.com/27705/178801539-957da96d-baa5-488f-828a-68dc90bf1581.png">

**Comment by briis** [comment]
The discrepancy is 0.036 inHg for Sealevel. It seems like a small number, but cannot be explained by a timing difference.
When you go in to the App, and click the Tempest icon in the upper right corner, and then scroll down you can see the 
Station Pressure. Could see if that is a match to what you see in the App - This is raw data from the station, so no conversion is done on that.

Just another check - Do you have exact the Altitude in the App as you use in Docker container - this also influences the Sealevel pressure.

**Comment by zacs** [comment]
> Just another check - Do you have exact the Altitude in the App as you use in Docker container - this also influences the Sealevel pressure.

Ignore my pressure stuff, my lat/long are not identical between the app and container. Totally didn't think of that. 🤦

**Comment by briis** [comment]
Back to the missing Zambretti data.
The text depends on the Zambretti number, so if this is None you will not get that.

The number depends on the following values: `latitude`, `Wind Direction Avg. (Degree)`, `Pressure High Value`, `Pressure Low Value`, `Pressure Trend (Numeric Value)` and `Sealevel Pressure`. If any of these are None, then you will get None back.

So can you check all the above values, and ensure that they provide values - It can take up to a minute after restart.

**Comment by zacs** [comment]
I've got a Tempest coming shortly (UV sensor failing on my Sky and lightning sensor failing on Air), so I am very interested to see if once it's add the Zembretti "just works." Happy to keep trying to debug in the meantime but that might be the real solution.

**Comment by GlennGoddard** [comment]
I would like to fix this, but I don't know where the issue is.  You have all the inputs for Zambretti, so you 'should' have it.  The only real difference between Air&Sky and Tempest are the UDP brodcasts, but other calculated sensors work for Air&Sky.

I'm at a loss.  Let us know the outcome of the Tempest, if there is still an issue then it might be something external to the weather devices.

**Comment by zacs** [comment]
Drum roll... just installed the Tempest and all the values are there as expected! So I suppose there's some sort of race condition when having two sensors. In any case, all is well, and I think we can close this since I may have been the only person alive with an Air/Sky that was interested in Zambretti. 😄

**Comment by briis** [comment]
Sounds good. When I am back from vacation I'll setup my Air/Sky just to see if I can replicate the behavior you have experienced. But glad it works for you now.

**Comment by briis** [comment]
Sounds good. When I am back from vacation I'll setup my Air/Sky just to see if I can replicate the behavior you have experienced. But glad it works for you now.
