### ISSUE TITLE
Container restarted on daily forecast unavailable

### ISSUE THREAD

**Issue by chasut** [briis/hass-weatherflow2mqtt#24]
Just FYI.
This afternoon, noticed that the daily forecast from the SmartWeather integration dropped out, loosing the forecast and related sensors.  I initially didn't notice the same drop from weatherflow2mqtt, but after looking at the container, it did drop and the container had to restart, although I have it set to do so automatically.  All in all, it recovered much quicker, but did require a restart.

This was clearly an issue on the WeatherFlow end as it happened to both simultaneously.  But oddly, didn't appear to have any effect on the hourly version of the SmartWeather or weatherflow2mqtt data.

Snap of the logs below.  
![Screen Shot 2021-06-15 at 8 05 03 PM](https://user-images.githubusercontent.com/42701104/122142890-f1206800-ce15-11eb-85ab-a8b97aaba700.png)

**Comment by GlennGoddard** [comment]
He recently improved error handling, do you have a recent pull?
Be advised that the latest change is a breaking change and will rename the sensors.

**Comment by briis** [comment]
I am not sure I catch the above error, so I will make sure that an unresponsive response from the WeatherFlow forecast, will not kill the container, but just let it wait until the next update.

**Comment by briis** [comment]
Hi both,
I have now released 2.0.2, which involved a lot of new coding. It is available now, but before I post this to the community on WeatherFlow, I would hope you could both upgrade and tell me if it works for you.

Here is the CHANGELOG:

**Please make a backup of `weatherflow2mqtt.db` before upgraing. Just in case anything goes wrong.**

`FIX`: If the forecast data from WeatherFlow is not available, the program will now just skip the update, and wait for the next timely update, instead of crashing the Container.

`CHANGED`: Attributes for each sensors are now moved from the event topics, to each individual sensor, so that we can add sensor specific attributes. This will have no impact on a running system.

`NEW`: Started the work on creating Sensors for High and Low values. A new table is created and daily high/low will be calculated and written to this table. Currently only day high and low plus all-time high and low values are calculated. The values are written as attributes to each individual sensor where I believe it is relevant to have these values.

| Attribute Name   | Description   |
| --- | --- |
| `max_day` | Maximum value for the current day. Reset at midnight. |
| `max_day_time` | UTC time when the max value was recorded. Reset at midnight. |
| `min_day` | Minimum value for the current day. Reset at midnight. |
| `min_day_time` | UTC time when the min value was recorded. Reset at midnight. |
| `max_all` | Maximum value ever recorded. Updated at midnight every day. |
| `max_all_time` | UTC time when the all-time max value was recorded. Updated at midnight every day. |
| `min_all` | Minimum value ever recorded. Updated at midnight every day. |
| `min_all_time` | UTC time when the all-time min value was recorded. Updated at midnight every day. |

The following sensors are displaying Max and Min values:

| Sensor ID   | Max Value   | Min Value   |
| --- | --- | --- |
| `air_temperature` | Yes | Yes |
| `dewpoint` | Yes | Yes |
| `illuminance` | Yes | No |
| `lightning_strike_count_today` | Yes | No |
| `lightning_strike_energy` | Yes | No |
| `rain_rate` | Yes | No |
| `rain_duration_today` | Yes | No |
| `relative_humidity` | Yes | Yes |
| `sealevel_pressure` | Yes | Yes |
| `solar_radiation` | Yes | No |
| `uv` | Yes | No |
| `wind_gust` | Yes | No |
| `wind_lull` | Yes | No |
| `wind_speed_avg` | Yes | No |

**Comment by GlennGoddard** [comment]
Timing...I will test it in about 10 hours when I get back home.  If I can distract the kids long enough, I will even unplug my internet router and see if what happens.

**Comment by chasut** [comment]
Wow, very pleasant surprise.  Just installed, and everything appears to be fine.  BTW, really appreciate the recent change to add the wf_ prefix, so checking all these sensors is much easier!  The first post of the min/max attributes showed up at the 10 minute mark.  Didn't peak at your code, was thinking it might be as much as 30 minutes before the write.  Of course I won't get a full day of data for a while, but all looks good so far.

Confession:  I just scanned your post and updated.  Wasn't till I came back to see your caution about backing up .db  oops.  No issue though, all is running well.

Thanks

**Comment by briis** [comment]
@GlennGoddard No problem. It is late afternoon here, and I am going out tonight, so no more work before tomorrow.

@chasut Glad it worked out, despite the missing backup 😬 No the data collection will start at first installation, so no history. I was considering to get the data from WeatherFlow, but decided not to go that route - there is no reason to replicate the data that all stations send to WF already - this is only to get some data in to HA.

**Comment by briis** [comment]
And btw, I bumped it to 2.0.3, and added the visibility sensor also.

**Comment by simonranson** [comment]
Working nicely on the Pi too - we've got some crazy weather here today in the south of the UK, so seeing lots of data coming in :)

**Comment by briis** [comment]
@simonranson Thanks for the feedback Simon. It is on my list to learn how to build for different platforms, so you don't have to build it yourself.

We also have another kind of crazy weather here in Denmark. 30 degrees Celsius which is not normal for Denmark, and especially not this early in the summer. For me heat like, needs to be enjoyed in Spain with a Cold Beer.

**Comment by GlennGoddard** [comment]
So far so good, I have the daily temperature min and max monitoring displayed.
Tomorrow I should know if the other sensors work after they update at midnight.

**Comment by briis** [comment]
Closing this now, as this was delivered in 2.0.2
