### ISSUE TITLE
External database

### ISSUE THREAD

**Issue by PianSom** [briis/hass-weatherflow2mqtt#61]
Thanks for all the work! I just got a Tempest in the UK yesterday (early access program) and have implemented weatherflow2mqtt into my existing flow with zero issues.

So this is a query/request rather than an issue: have you considered allowing using an external database - I am thinking influxdb - rather than (or as well as) the internal one for data storage? 

The advantage of this would be to allow the data to be used for other purposes (like [this](https://community.weatherflow.com/t/a-few-grafana-dashboards-for-tempest/12185) for data display, which is more flexible that HA). I did look in to the possibility of having multiple containers listen on 50222 but that looks like a non-starter. As a stop-gap I am exporting to influx from HA, but I would rather avoid the intermediate step and possibly use the existing Grafana dashboards that have already been created

**Comment by briis** [comment]
I am not sure what the real benefit would be. There is a SQLite database used by the system, but basically this is only there because some of the sensors require some temporary data stored in order to calculate correct values and because there is no history when you restart your WeatherFlow.
HA will not function without storing data in the HA Database, so that needs to be done anyway, and exporting them to InfluxDB for reporting is pretty easy.

So unless I totally misunderstood your request, I don't think I will do this for now.

**Comment by PianSom** [comment]
Completely understand your reasoning.

But, just to make myself clear, I want to use both HA and Grafana to look at weatherflow data. (HA so I can incorporate automations, Grafana because it is far better for look at time series data.) I'll just carry on having two containers (on two machines) - it's not that much of a burden. And this way is (possibly, probably) more reliable than exporting from HA to Influxdb

Thanks again for the work in producing and maintaining this great tool
