### ISSUE TITLE
Current condition Icons

### ISSUE THREAD

**Issue by robertw** [briis/hass-weatherflow2mqtt#67]
Just a suggestion for a future enhancement I'm sure it is possible but if someone's willing to tackle it the ability to show current condition related to an icon like one the animated ones used in weather cards we could define them in the config this way not to infringe on any copyrights etc. and have the ability to use custom sets as you please

Of course taking into consideration Cloud Luxe temperature weather conditions as far as precipitation is concerned etcetera in real time

Regards
Robert

**Comment by GlennGoddard** [comment]
That think would be outside of the ability of this integration; that would have to be a custom weather card of some type to change the icons.  You can however bring all of this into a weather card but defining the icons would have to happen in that card since Home Assistant uses a set of inputs for weather.  I am working on the 'current conditions' to be generated locally like sunny, foggy, night but there is a lot to it (see other issue in list).

**Comment by briis** [comment]
I agree with @GlennGoddard. This Integration just supplies states for the icons, and then the HA UI, should be where the actual icons are selected and displayed in the different built-in or custom cards.. So I will close this now.
